### ISSUE TITLE
Promise that you will never ask for donations in the sneedacity.org page

### ISSUE THREAD

**Issue by ImGonnaChuck** [Sneeds-Feed-and-Seed/sneedacity.org#2]
@parkbanks

**Comment by parkbanks** [comment]
I have no interest in or intentions towards asking for personal donations on sneedacity.org. However, there has been some discussion as to whether a paragraph should be added to the about section, directing users to donate to the FSF (or another charitable organization), rather than to the project developers. Regardless, such issues are ultimately not my decision.
